### PR TITLE
little fixes & tutorial link

### PR DESCRIPTION
**Pull request by uguryuruk**
Hello @anburocky3 ,

I have some little fixes and a added a tutorial link! I have shot a video tutorial on Youtube. 

I hope that will boost the number of downloads!

### CODE REVIEW

**Comment by anburocky3** [comment]
Looks good, Do you have any other fixes to be mentioned in this PR? 

Your video is good, the effort you have put into this is appreciatable. 👏

**Comment by uguryuruk** [comment]
No, I have spotted only three little bugs. If you have any, please tell me and I will check.

**Comment by anburocky3** [comment]
> No, I have spotted only three little bugs. If you have any, please tell me and I will check.

Done, let's proceed with this for now. And we have to look at the bootstrap docs for any improvement or breaking changes, so we should update the template, accordingly. Thanks, will merge it now.

**Comment by anburocky3** [comment]
Thank you for your contribution. Merged.

**Comment by anburocky3** [comment]
Thank you @uguryuruk , have mentioned the special thanks appreciation on the readme docs. Thanks.

**Pull request merged**
